### ISSUE TITLE
Can't select article from page type "Folder" (contao-folderpage)

### ISSUE THREAD

**Issue by Stefko** [bastibuck/contao-article-as-module#3]
I'm using c-a-a-m combined with the terminal42/contao-folderpage extension (Contao 4.4.20) and I can't select articles classified to the page-type "Folder" (new page-type provided by contao-folderpage). The folder page isn't shown in the dropdown menu.

I'm not completely shure, but I think this combination worked fine in Contao 3.5x

**Comment by bastibuck** [comment]
Can you verify if it works in a 3.5.x? How about a 4.5?

**Comment by Stefko** [comment]
Sorry, my fault I was wrong. The combination also doesn't work in Contao 3.5

I think a solution could be to extend the `$objPages` in line 66 of `dca/tl_module.php` to the page-type '`folder`'.
What do you think?

**Comment by bastibuck** [comment]
Okay, yeah looking at the line it actually can't work in any Contao version with the mentioned extension `folderpage`. 

Speaking of which as it is not a core extension I really don't want to include this conditional in my extension. Where would I be going if more extension pop up that add more page types?! 

I see some options here:
1. You override my function in a custom funtion inside a function of yours and manipulate the return by adding the articles for folder pages: `myClass extends \Bastibuck\tl_module` `$return = parent::getArticlesPerPage();`  You would have to register it to contao as an option callback like so https://github.com/bastibuck/contao-article-as-module/blob/master/dca/tl_module.php#L26 
1. I can include a Hook to make it easier to plug into the existing method to manipulate the articles array.
1. I add a new extension that requires this one and adds the `folder` page articles if installed. 
1. I simply add the code in here as `folderpage` is a great extension. 

What do you think? 
Why do you have articles inside your `folders` in the first place?

**Comment by Stefko** [comment]
Hi, thanks for your description.
I think I will try my luck with option 1) even though I never done something before and I'm not very experienced with such things. Anyway, learning by doing ;-)
But 3 or 4 as well would be great :-)

> Why do you have articles inside your folders in the first place?
> 
Good question ... hmmm, kind of workflow. I want to use these articles as a kind of content-container for the header and footer and include them as a module to the suitable page-layout.

**Comment by bastibuck** [comment]
> Good question ... hmmm, kind of workflow. I want to use these articles as a kind of content-container for the header and footer and include them as a module to the suitable page-layout.

Why don't you just use a regular page then and hide it from the nav or even make it unpublished? 
That's how I always go about it. Create a page called "Includes" that contains all the different articles I want to include elsewhere (just like you mention in Footer for example). 
That's also why I created this extension in the first place. 

In my understanding a folder pagetype is for structuring pages not to contain content...

**Comment by Stefko** [comment]
> Why don't you just use a regular page then and hide it from the nav or even make it unpublished?
>
Yep, that's the way I worked in the past too. After finding the folder-page extension I thought it's a nice idea to collect all my "include articels" in a folder instead of a page. Because to get a bit more structure to my backend.

> In my understanding a folder pagetype is for structuring pages not to contain content...
> 
Meanwhile I'm thinking you're right and I'll do it with a "Includes-Page" in the future again.

**Comment by bastibuck** [comment]
I also combine folderpage with my includes and use a folder "includes" that holds all my pages that contain include-articles. This way it gives structure and works perfectly fine.

So I'm closing this since we don't need folderpages to hold articles to include via this extension. Otherwise feel free to re-open.
